# Generated by Django 2.1.3 on 2018-12-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clnt_id', models.IntegerField(blank=True, db_column='CLNT_ID', null=True)),
                ('clnt_gender', models.CharField(blank=True, db_column='CLNT_GENDER', max_length=10, null=True)),
                ('clnt_age', models.IntegerField(blank=True, db_column='CLNT_AGE', null=True)),
            ],
            options={
                'db_table': 'custom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_c', models.IntegerField(blank=True, db_column='PD_C', null=True)),
                ('pd_nm', models.CharField(blank=True, db_column='PD_NM', max_length=50, null=True)),
                ('clac1_nm', models.CharField(blank=True, db_column='CLAC1_NM', max_length=50, null=True)),
                ('clac2_nm', models.CharField(blank=True, db_column='CLAC2_NM', max_length=50, null=True)),
                ('clac3_nm', models.CharField(blank=True, db_column='CLAC3_NM', max_length=50, null=True)),
            ],
            options={
                'db_table': 'master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clnt_id', models.IntegerField(blank=True, db_column='CLNT_ID', null=True)),
                ('sess_id', models.IntegerField(blank=True, db_column='SESS_ID', null=True)),
                ('hits_seq', models.IntegerField(blank=True, db_column='HITS_SEQ', null=True)),
                ('pd_c', models.IntegerField(blank=True, db_column='PD_C', null=True)),
                ('pd_add_nm', models.CharField(blank=True, db_column='PD_ADD_NM', max_length=50, null=True)),
                ('pd_bra_nm', models.CharField(blank=True, db_column='PD_BRA_NM', max_length=50, null=True)),
                ('pd_buy_am', models.IntegerField(blank=True, db_column='PD_BUY_AM', null=True)),
                ('pd_buy_ct', models.IntegerField(blank=True, db_column='PD_BUY_CT', null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clnt_id', models.IntegerField(blank=True, db_column='CLNT_ID', null=True)),
                ('sess_id', models.IntegerField(blank=True, db_column='SESS_ID', null=True)),
                ('kwd_nm', models.CharField(blank=True, db_column='KWD_NM', max_length=50, null=True)),
                ('search_cnt', models.IntegerField(blank=True, db_column='SEARCH_CNT', null=True)),
            ],
            options={
                'db_table': 'search1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Search2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sess_dt', models.IntegerField(blank=True, db_column='SESS_DT', null=True)),
                ('kwd_nm', models.CharField(blank=True, db_column='KWD_NM', max_length=50, null=True)),
                ('search_cnt', models.IntegerField(blank=True, db_column='SEARCH_CNT', null=True)),
            ],
            options={
                'db_table': 'search2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clnt_id', models.CharField(blank=True, db_column='CLNT_ID', max_length=50, null=True)),
                ('sess_id', models.CharField(blank=True, db_column='SESS_ID', max_length=50, null=True)),
                ('sess_seq', models.IntegerField(blank=True, db_column='SESS_SEQ', null=True)),
                ('sess_dt', models.DateField(blank=True, db_column='SESS_DT', null=True)),
                ('tot_pag_view_ct', models.IntegerField(blank=True, db_column='TOT_PAG_VIEW_CT', null=True)),
                ('tot_sess_hr_v', models.IntegerField(blank=True, db_column='TOT_SESS_HR_V', null=True)),
                ('dvc_ctg_nm', models.CharField(blank=True, db_column='DVC_CTG_NM', max_length=50, null=True)),
                ('zon_nm', models.CharField(blank=True, db_column='ZON_NM', max_length=50, null=True)),
                ('city_nm', models.CharField(blank=True, db_column='CITY_NM', max_length=50, null=True)),
                ('day', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'session',
                'managed': False,
            },
        ),
    ]
